AWSTemplateFormatVersion: "2010-09-09"

Description: (SO0189n-export) QnABot nested Amazon Kendra index

Parameters:

  IndexName:
    Type: String

  IndexEdition:
    Type: String
    Default: DEVELOPER_EDITION
    AllowedValues:
      - DEVELOPER_EDITION
      - ENTERPRISE_EDITION

Resources:

  KendraIndexRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: ''
            Effect: Allow
            Principal:
              Service: kendra.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Resource: '*'
                Condition:
                  StringEquals:
                    'cloudwatch:namespace': 'Kendra'
                Action:
                  - 'cloudwatch:PutMetricData'
              - Effect: Allow
                Resource: '*'
                Action: 'logs:DescribeLogGroups'
              - Effect: Allow
                Resource: !Sub
                  - 'arn:aws:logs:${region}:${account}:log-group:/aws/kendra/*'
                  - region: !Ref 'AWS::Region'
                    account: !Ref 'AWS::AccountId'
                Action: 'logs:CreateLogGroup'
              - Effect: Allow
                Resource: !Sub
                  - 'arn:aws:logs:${region}:${account}:log-group:/aws/kendra/*:log-stream:*'
                  - region: !Ref 'AWS::Region'
                    account: !Ref 'AWS::AccountId'
                Action: 
                  - 'logs:DescribeLogStreams'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
          PolicyName: KendraMediaIndexPolicy
      
  KendraIndex:
    Type: 'AWS::Kendra::Index'
    Properties:
      Name: !Ref IndexName
      Edition: !Ref IndexEdition
      RoleArn: !GetAtt KendraIndexRole.Arn

Outputs:

  KendraIndexId:
    Description: Kendra Index ID
    Value: !GetAtt KendraIndex.Id